wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720479095
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      - 98
      3:
      - 13
      - 23
      4: 3.10.14
      5: 0.17.2
      6: 4.40.1
      8:
      - 5
      13: linux-x86_64
